//! Regenerate `data/*.yaml` from CommunityDragon's TFT export.
//!
//! ```text
//! curl -L https://raw.communitydragon.org/latest/cdragon/tft/en_us.json -o en_us.json
//! cargo run -p tft-synapse-data --example import_cdragon -- en_us.json crates/tft-data/data
//! ```
//!
//! Picks the newest standard set: the highest `setData` entry whose mutator is
//! `TFTSet<N>` and whose units are named `TFT<N>_...` (special modes such as
//! event sets use other prefixes). Writes real champions (cost, traits),
//! traits (breakpoints), the 9 basic components and the completed items made
//! from them, and the set's augments with their rarity. CommunityDragon has
//! no win-rate data, so augments get no power tier and a neutral score.

use std::collections::{BTreeSet, HashMap};
use std::path::Path;

use serde::Serialize;
use serde_json::Value;

#[derive(Serialize)]
struct Champion {
    name: String,
    cost: u8,
    traits: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    role: Option<String>,
}

#[derive(Serialize)]
struct Trait {
    name: String,
    r#type: String,
    breakpoints: Vec<u8>,
}

#[derive(Serialize)]
struct Item {
    name: String,
    category: &'static str,
    is_component: bool,
    tags: Vec<String>,
}

#[derive(Serialize)]
struct Augment {
    name: String,
    tier: Option<String>,
    base_score: f32,
    tags: Vec<String>,
}

/// What a basic component contributes: (category, tag).
fn component_kind(api: &str) -> (&'static str, &'static str) {
    match api {
        "TFT_Item_BFSword" => ("AttackDamage", "AD"),
        "TFT_Item_RecurveBow" => ("AttackSpeed", "AS"),
        "TFT_Item_NeedlesslyLargeRod" => ("AbilityPower", "AP"),
        "TFT_Item_TearOfTheGoddess" => ("Mana", "mana"),
        "TFT_Item_ChainVest" => ("Tank", "armor"),
        "TFT_Item_NegatronCloak" => ("Tank", "magic-resist"),
        "TFT_Item_GiantsBelt" => ("Tank", "health"),
        "TFT_Item_SparringGloves" => ("CriticalStrike", "crit"),
        _ => ("Utility", "utility"),
    }
}

fn s(v: &Value) -> String {
    v.as_str().unwrap_or_default().to_owned()
}

fn write_yaml<T: Serialize>(dir: &Path, file: &str, key: &str, version: &str, rows: &[T]) {
    let mut doc = serde_yaml::Mapping::new();
    doc.insert("meta_version".into(), version.into());
    doc.insert(
        key.into(),
        serde_yaml::to_value(rows).expect("rows serialize"),
    );
    let text = format!(
        "# Generated by `cargo run -p tft-synapse-data --example import_cdragon` from\n# CommunityDragon ({version}). Do not edit by hand.\n{}",
        serde_yaml::to_string(&doc).expect("yaml")
    );
    std::fs::write(dir.join(file), text).expect("write yaml");
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let (src, out) = match (args.get(1), args.get(2)) {
        (Some(s), Some(o)) => (s.clone(), o.clone()),
        _ => {
            eprintln!("usage: import_cdragon <en_us.json> <data dir>");
            std::process::exit(2);
        }
    };
    let root: Value = serde_json::from_str(&std::fs::read_to_string(&src).expect("read json"))
        .expect("parse json");
    let items: HashMap<String, &Value> = root["items"]
        .as_array()
        .expect("items")
        .iter()
        .map(|i| (s(&i["apiName"]), i))
        .collect();

    // Newest standard set.
    let set = root["setData"]
        .as_array()
        .expect("setData")
        .iter()
        .filter(|sd| {
            let n = sd["number"].as_u64().unwrap_or(0);
            let prefix = format!("TFT{n}_");
            sd["mutator"].as_str() == Some(&format!("TFTSet{n}"))
                && sd["champions"]
                    .as_array()
                    .is_some_and(|cs| cs.iter().any(|c| s(&c["apiName"]).starts_with(&prefix)))
        })
        .max_by_key(|sd| sd["number"].as_u64().unwrap_or(0))
        .expect("a standard set");
    let number = set["number"].as_u64().unwrap_or(0);
    let version = format!("Set {number}");
    let prefix = format!("TFT{number}_");

    let mut champions: Vec<Champion> = set["champions"]
        .as_array()
        .expect("champions")
        .iter()
        // `..._TraitClone` units only list the traits a player can pick.
        .filter(|c| {
            let api = s(&c["apiName"]);
            api.starts_with(&prefix) && !api.contains("TraitClone")
        })
        .filter_map(|c| {
            let cost = c["cost"].as_u64()? as u8;
            // "Choose Trait" is a placeholder for a trait the player picks in
            // game (Miss Fortune in Set 17); it has no breakpoints.
            let traits: Vec<String> = c["traits"]
                .as_array()?
                .iter()
                .map(s)
                .filter(|t| t != "Choose Trait")
                .collect();
            ((1..=5).contains(&cost) && !traits.is_empty()).then(|| Champion {
                name: s(&c["name"]),
                cost,
                traits,
                role: c["role"].as_str().map(str::to_owned),
            })
        })
        .collect();
    champions.sort_by(|a, b| a.cost.cmp(&b.cost).then(a.name.cmp(&b.name)));
    champions.dedup_by(|a, b| a.name == b.name);

    let mut traits: Vec<Trait> = set["traits"]
        .as_array()
        .expect("traits")
        .iter()
        .map(|t| Trait {
            name: s(&t["name"]),
            r#type: "trait".into(),
            breakpoints: t["effects"]
                .as_array()
                .map(|es| {
                    es.iter()
                        .filter_map(|e| e["minUnits"].as_u64().map(|n| n as u8))
                        .collect()
                })
                .unwrap_or_default(),
        })
        .filter(|t| !t.breakpoints.is_empty())
        .collect();
    traits.sort_by(|a, b| a.name.cmp(&b.name));

    // Completed items: two basic components; components: whatever they are made of.
    let set_items: Vec<&Value> = set["items"]
        .as_array()
        .expect("items")
        .iter()
        .filter_map(|a| items.get(a.as_str()?).copied())
        .collect();
    let completed: Vec<&Value> = set_items
        .iter()
        .copied()
        .filter(|i| {
            let api = s(&i["apiName"]);
            api.starts_with("TFT_Item_")
                && !api.contains("Emblem")
                && i["composition"].as_array().is_some_and(|c| c.len() == 2)
        })
        .collect();
    let components: BTreeSet<String> = completed
        .iter()
        .flat_map(|i| i["composition"].as_array().into_iter().flatten().map(s))
        .collect();
    let mut item_rows: Vec<Item> = components
        .iter()
        .filter_map(|api| items.get(api))
        .map(|i| {
            let (category, tag) = component_kind(&s(&i["apiName"]));
            Item {
                name: s(&i["name"]),
                category,
                is_component: true,
                tags: vec![tag.into()],
            }
        })
        .collect();
    let mut done: Vec<Item> = completed
        .iter()
        .map(|i| {
            let parts: Vec<String> = i["composition"]
                .as_array()
                .into_iter()
                .flatten()
                .map(s)
                .collect();
            let (category, _) = component_kind(&parts[0]);
            let mut tags: Vec<String> = parts
                .iter()
                .map(|p| component_kind(p).1.to_owned())
                .collect();
            tags.dedup();
            Item {
                name: s(&i["name"]),
                category,
                is_component: false,
                tags,
            }
        })
        .collect();
    done.sort_by(|a, b| a.name.cmp(&b.name));
    item_rows.extend(done);

    let mut augments: Vec<Augment> = set["augments"]
        .as_array()
        .expect("augments")
        .iter()
        .filter_map(|a| items.get(a.as_str()?))
        .map(|a| {
            let icon = s(&a["icon"]).to_lowercase();
            let rarity = if icon.ends_with("-iii.tex") || icon.ends_with("-iii.png") {
                "prismatic"
            } else if icon.ends_with("-ii.tex") || icon.ends_with("-ii.png") {
                "gold"
            } else {
                "silver"
            };
            // Tags come from what the augment's description says, so the
            // advisor's explanations ("strong early", "comeback option") rest
            // on the augment's text rather than on invented ratings.
            let desc = s(&a["desc"]).to_lowercase();
            let mut tags = vec![rarity.to_owned()];
            let mut tag = |t: &str, words: &[&str]| {
                if words.iter().any(|w| desc.contains(w)) {
                    tags.push(t.to_owned());
                }
            };
            tag("econ", &["gold", "interest", "reroll"]);
            tag("AP", &["ability power"]);
            tag("AD", &["attack damage"]);
            tag("tank", &["armor", "magic resist", "health", "shield"]);
            tag(
                "scaling",
                &["permanently", "each round", "every round", "round start"],
            );
            tag(
                "comeback",
                &[
                    "lose a player combat",
                    "after losing",
                    "losing streak",
                    "when you lose",
                ],
            );
            tag("items", &["component", "item anvil", "completed item"]);
            Augment {
                name: s(&a["name"]),
                tier: None,
                base_score: 50.0,
                tags,
            }
        })
        .filter(|a| !a.name.is_empty())
        .collect();
    augments.sort_by(|a, b| a.name.cmp(&b.name));
    augments.dedup_by(|a, b| a.name == b.name);

    let dir = Path::new(&out);
    write_yaml(dir, "champions.yaml", "champions", &version, &champions);
    write_yaml(dir, "traits.yaml", "traits", &version, &traits);
    write_yaml(dir, "items.yaml", "items", &version, &item_rows);
    write_yaml(dir, "augments.yaml", "augments", &version, &augments);
    println!(
        "{version}: {} champions, {} traits, {} items ({} components), {} augments",
        champions.len(),
        traits.len(),
        item_rows.len(),
        components.len(),
        augments.len()
    );
}
